name: Bug Report
description: Submit a bug report for ATCTrainer.
title: "[BUG] "
labels: [bug]
assignees: collink2451
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Do not repeat a bug report or include a new feature request.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please include a clear and concise description of what the bug is.
      placeholder: 
    validations:
      required: true
  - type: input
    id: error
    attributes:
      label: What error response was returned (if applicable)?
      description: The error response.
      placeholder: 
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Link to screenshots, if applicable.
      placeholder: 
    validations:
      required: false
